version: '3.1'

services:
  xdai:
    image: nethermind/nethermind:latest
    expose:
      - "8545"
      - "40444"
    ports:
      - "40444:40444"
      - "40444:40444/udp"
    volumes:
      - xdai:/nethermind_db/xdai
      - ./xdai/xdai.cfg:/xdai.cfg
      - ./xdai/xdai.json:/xdai.json
    networks:
      - chains
    command: "--config /xdai.cfg"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.xdai-stripprefix.stripprefix.prefixes=/xdai"
      - "traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange=$WHITELIST"
      - "traefik.http.services.xdai.loadbalancer.server.port=8545"
      - "traefik.http.routers.xdai.entrypoints=websecure"
      - "traefik.http.routers.xdai.tls.certresolver=myresolver"
      - "traefik.http.routers.xdai.rule=Host(`$DOMAIN`) && PathPrefix(`/xdai`)"
      - "traefik.http.routers.xdai.middlewares=xdai-stripprefix, ipwhitelist"

volumes:
    xdai:  