{
 "title": "Node1 Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Node1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Relay Counter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pocketcore_service_relay_count_for_0040"
    },
    {
     "expr": "pocketcore_service_relay_count_for_0021{}"
    },
    {
     "expr": "pocketcore_service_relay_count_for_0005"
    },
    {
     "expr": "pocketcore_service_relay_count_for_0023"
    },
    {
     "expr": "pocketcore_service_relay_count_for_0026"
    },
    {
     "expr": "pocketcore_service_relay_count_for_0027{}"
    }
   ]
  },
  {
   "title": "Token Rewards",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pocketcore_service_tokens_earned_for_all{}"
    }
   ]
  },
  {
   "title": "Total Relays ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pocketcore_service_relay_count_for_all{}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Block Height",
   "type": "stat",
   "description": "Height of the chain",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tendermint_consensus_height" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "description": "Number of peers node's connected to\n\n(Need to change Threshold)",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_p2p_peers" }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "stat",
   "description": "Total voting power of all validators",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power"
    }
   ]
  },
  {
   "title": "Consensus Rounds At Current Height",
   "type": "stat",
   "description": "Number of rounds",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_consensus_rounds" }
   ]
  },
  {
   "title": "Transactions At Current Height",
   "type": "stat",
   "description": "Number of transactions",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_consensus_num_txs" }
   ]
  },
  {
   "title": "Confirmed Transactions",
   "type": "stat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_consensus_total_txs" }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "stat",
   "description": "Block size in bytes",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes"
    }
   ]
  },
  {
   "title": "Block TIme (seconds)",
   "type": "graph",
   "description": "Time between this and last block (Block.Header.Time) in seconds",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds"
    }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "STEAK" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power"
    }
   ]
  },
  { "title": "Mempool Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Unconfirmed",
   "type": "stat",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_mempool_size" }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Cumulative count",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_mempool_failed_txs" }
   ]
  },
  {
   "title": "Rechecked",
   "type": "stat",
   "description": "Cumulative count",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_recheck_times"
    }
   ]
  },
  {
   "title": "Size (bytes)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_tx_size_bytes_count"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators-tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "Missing",
   "type": "stat",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "Byzantine",
   "type": "stat",
   "description": "Number of validators who tried to double sign",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators"
    }
   ]
  },
  {
   "title": "% of (Missing+Byzantine)",
   "type": "stat",
   "description": "Percentage of missing + byzantine validators",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((tendermint_consensus_byzantine_validators_power + tendermint_consensus_missing_validators_power) / tendermint_consensus_validators_power) * 100"
    }
   ]
  },
  {
   "title": "Voting Power of Missing",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power"
    }
   ]
  },
  {
   "title": "Voting Power of Byzantine",
   "type": "stat",
   "description": "Total voting power of the byzantine validators",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators_power"
    }
   ]
  },
  {
   "title": "Missing Validators History",
   "type": "graph",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators"
    }
   ]
  }
 ]
}