{
 "title": "Pokt Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "pocket-fr-1:8083,pocket-fr-2:8083"
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Relays per Chain",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pocketcore_service_relay_count_for_0001{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "relays for pocket"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0005{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "relays for fuse"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0021{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "relays for eth-mainnet"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0022{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "relays for eth-archive"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0023{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "relays for ropsten"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0025{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "relays for rinkeby"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0026{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "relays for goerli"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0027{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "relays for xdai"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0028{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "relays for eth-arch-trace"
    },
    {
     "expr": "rate(pocketcore_service_relay_count_for_0040{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "relays for harmony"
    }
   ]
  },
  {
   "title": "Error count all Chains",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pocketcore_service_err_count_for_all{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Avg relay time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0001_bucket{instance=~\"$instance\"}[1m])))",
     "legendFormat": "relay time 0001"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0021_bucket{instance=~\"$instance\"}[1m])))",
     "legendFormat": "relay time 0021"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0026_bucket{instance=~\"$instance\"}[1m])))",
     "legendFormat": "relay time 0026"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0028_bucket{instance=~\"$instance\"}[1m])))",
     "legendFormat": "relay time 0028"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_0040_bucket{instance=~\"$instance\"}[1m])))",
     "legendFormat": "relay time 0040"
    }
   ]
  },
  {
   "title": "Session count per Chain Both nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0001{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "pocket"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0005{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "fuse"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0021{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "eth-mainnet"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0022{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "eth-archive"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0023{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "eth-ropsten"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0025{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "eth-rinkeby"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0026{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "eth-goerli"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0027{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "xdai"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0028{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "eth-archive-trace"
    },
    {
     "expr": "rate(pocketcore_service_sessions_count_for_0040{instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "harmony"
    }
   ]
  },
  {
   "title": "Consensus Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "latest_block_height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Block Processing Time sum / count",
   "type": "status-history",
   "description": "Block Processing Time sum / count",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "tendermint_state_block_processing_time_sum{instance=~\"$instance\"} / tendermint_state_block_processing_time_count{instance=~\"$instance\"}",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "block interval",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "Peers {{ job }}"
    }
   ]
  },
  {
   "title": "consensus_validators_power",
   "type": "gauge",
   "description": "Total voting power of all validators",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "missing_validators",
   "type": "gauge",
   "description": "consensus_missing_validators",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "mempool tx size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tendermint_mempool_tx_size_bytes_bucket{instance=~\"$instance\"}[1m])))"
    }
   ]
  },
  {
   "title": "Avg relay time for all chains",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(pocketcore_service_avg_relay_time_for_all_bucket{instance=~\"$instance\"}[1m])))",
     "legendFormat": "avg relay all bucket"
    }
   ]
  },
  {
   "title": "p2p_peer_send_bytes",
   "type": "timeseries",
   "description": "number of bytes per channel sent to a given peer",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(tendermint_p2p_peer_send_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "Peer {{ peer_id }}"
    }
   ]
  }
 ]
}