{
 "title": "traefik",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Requests POKT-FR-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(traefik_service_requests_total{instance=\"traefik:8082\",service=\"pocket-fr-1@docker\"}[1m]) * 100",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Requests POKT-FR-2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(traefik_service_requests_total{instance=\"traefik:8082\",service=\"pocket-fr-2@docker\"}[1m]) * 100",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Requests SSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(traefik_service_requests_tls_total{instance=\"traefik:8082\",service=~\"pocket-fr-1@docker|pocket-fr-2@docker\"}[1m]) * 100",
     "legendFormat": "{{ tls_cipher }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "traefik_service_open_connections{instance=\"traefik:8082\",service=~\"pocket-fr-1@docker|pocket-fr-2@docker\"}",
     "legendFormat": "{{ method }} {{ service }}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(traefik_service_request_duration_seconds_count{instance=\"traefik:8082\",service=~\"pocket-fr-1@docker|pocket-fr-2@docker\"}[1m])",
     "legendFormat": "{{ code }} {{ method }} {{ service }}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(traefik_service_request_duration_seconds_bucket{instance=\"traefik:8082\",service=~\"pocket-fr-1@docker|pocket-fr-2@docker\"}[1m])))"
    }
   ]
  },
  {
   "title": "Sum Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{instance=\"traefik:8082\",service=~\"pocket-fr-2@docker\"}[1m])) by (method)",
     "legendFormat": "pokt-fr-1 {{ method }}"
    },
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_sum{instance=\"traefik:8082\",service=~\"pocket-fr-1@docker\"}[1m])) by (method)",
     "legendFormat": "pokt-fr-1 {{ method }}"
    }
   ]
  }
 ]
}